name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 1.12.1.1550

      - name: Cache Clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.gitlibs
            ~/.deps.clj
          key: clj-deps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test
